/**
 * Development Inspection Sample Data.
 * Strictly used as an opt-in fallback when backend endpoints are offline/in-progress.
 * NOT presented as real backend data.
 */

import type { Transaction } from '../types/transaction';
import type { DashboardStats } from '../types/dashboard';
import type { FraudAssessment } from '../types/fraud';

export const SAMPLE_DASHBOARD_STATS: DashboardStats = {
  totalTransactions: 1248,
  flaggedTransactions: 183,
  highRisk: 72,
  critical: 18,
  pendingReview: 54,
  cleared: 129,
  averageRiskScore: 42,
  fraudRatePercentage: 14.6,
};

export const SAMPLE_TRANSACTIONS: Transaction[] = [
  {
    id: 'TXN-10234',
    userId: 'USR-102',
    amount: 24500,
    currency: 'INR',
    location: 'Hyderabad, India',
    riskScore: 90,
    riskLevel: 'CRITICAL',
    status: 'PENDING',
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    merchant: 'FastPay Gateway',
    category: 'Electronics & Gadgets',
    paymentMethod: 'Credit Card (Visa)',
    ipAddress: '103.211.54.12',
    deviceFingerprint: 'DEV-7821-WIN',
    deviceInfo: {
      browser: 'Chrome 128.0',
      os: 'Windows 11',
      deviceId: 'DEV-7821',
      deviceType: 'Desktop',
    },
    isFlagged: true,
  },
  {
    id: 'TXN-10235',
    userId: 'USR-204',
    amount: 1250,
    currency: 'USD',
    location: 'New York, USA',
    riskScore: 72,
    riskLevel: 'HIGH',
    status: 'PENDING',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    merchant: 'Global Wire Transfer',
    category: 'Remittance',
    paymentMethod: 'ACH Transfer',
    ipAddress: '198.51.100.45',
    deviceFingerprint: 'DEV-9912-IOS',
    deviceInfo: {
      browser: 'Mobile Safari 17.4',
      os: 'iOS 17.5',
      deviceId: 'DEV-9912',
      deviceType: 'Mobile Phone',
    },
    isFlagged: true,
  },
  {
    id: 'TXN-10236',
    userId: 'USR-305',
    amount: 340,
    currency: 'EUR',
    location: 'Berlin, Germany',
    riskScore: 45,
    riskLevel: 'MEDIUM',
    status: 'REVIEWED',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    merchant: 'EuroStore Direct',
    category: 'Apparel',
    paymentMethod: 'Debit Card',
    ipAddress: '85.214.132.117',
    deviceFingerprint: 'DEV-4410-MAC',
    deviceInfo: {
      browser: 'Firefox 126.0',
      os: 'macOS Sonoma',
      deviceId: 'DEV-4410',
      deviceType: 'Laptop',
    },
    isFlagged: false,
  },
  {
    id: 'TXN-10237',
    userId: 'USR-411',
    amount: 85,
    currency: 'GBP',
    location: 'London, UK',
    riskScore: 12,
    riskLevel: 'LOW',
    status: 'CLEARED',
    timestamp: new Date(Date.now() - 110 * 60000).toISOString(),
    merchant: 'Metro Transit Co',
    category: 'Transportation',
    paymentMethod: 'Contactless NFC',
    ipAddress: '82.165.197.1',
    deviceFingerprint: 'DEV-1102-AND',
    deviceInfo: {
      browser: 'Chrome Mobile',
      os: 'Android 14',
      deviceId: 'DEV-1102',
      deviceType: 'Mobile',
    },
    isFlagged: false,
  },
  {
    id: 'TXN-10238',
    userId: 'USR-582',
    amount: 95000,
    currency: 'INR',
    location: 'Mumbai, India',
    riskScore: 95,
    riskLevel: 'CRITICAL',
    status: 'PENDING',
    timestamp: new Date(Date.now() - 150 * 60000).toISOString(),
    merchant: 'CryptoExchange P2P',
    category: 'Cryptocurrency',
    paymentMethod: 'UPI Direct',
    ipAddress: '157.34.19.88',
    deviceFingerprint: 'DEV-3301-LNX',
    deviceInfo: {
      browser: 'Brave 1.66',
      os: 'Linux x86_64',
      deviceId: 'DEV-3301',
      deviceType: 'Workstation',
    },
    isFlagged: true,
  },
  {
    id: 'TXN-10239',
    userId: 'USR-609',
    amount: 5200,
    currency: 'USD',
    location: 'San Francisco, USA',
    riskScore: 68,
    riskLevel: 'HIGH',
    status: 'REVIEWED',
    timestamp: new Date(Date.now() - 210 * 60000).toISOString(),
    merchant: 'Cloud Hosting Services',
    category: 'Software & Infrastructure',
    paymentMethod: 'Corporate Credit Card',
    ipAddress: '192.0.2.14',
    deviceFingerprint: 'DEV-8822-WIN',
    deviceInfo: {
      browser: 'Edge 125.0',
      os: 'Windows 11',
      deviceId: 'DEV-8822',
      deviceType: 'Desktop',
    },
    isFlagged: true,
  },
];

export const SAMPLE_FRAUD_ASSESSMENTS: Record<string, FraudAssessment> = {
  'TXN-10234': {
    transactionId: 'TXN-10234',
    riskScore: 90,
    riskLevel: 'CRITICAL',
    explanation:
      'This transaction was flagged because multiple high-risk indicators were detected, including abnormal transaction velocity, an unusually large amount relative to the user history, and an impossible geographic movement within 5 minutes.',
    summary: '3 critical and high fraud rules triggered concurrently.',
    evaluatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    rules: [
      {
        ruleName: 'Transaction Velocity',
        isTriggered: true,
        reason: '7 transactions occurred within 5 minutes across multiple endpoints.',
        evidence: '7 transactions within a 5-minute window (Threshold: max 3/5min).',
        scoreContribution: 25,
        severity: 'HIGH',
      },
      {
        ruleName: 'Unusual Amount',
        isTriggered: true,
        reason: 'Transaction amount is significantly higher than the user baseline range.',
        evidence: {
          currentAmount: '₹24,500',
          historicalAverage: '₹2,100',
          deviationRatio: '11.6x',
        },
        scoreContribution: 30,
        severity: 'CRITICAL',
      },
      {
        ruleName: 'Impossible Location',
        isTriggered: true,
        reason: 'Geographic jump detected that exceeds physical transit velocity limitations.',
        evidence: {
          previousCity: 'Tokyo, Japan',
          currentCity: 'Hyderabad, India',
          elapsedMinutes: 14,
          requiredVelocityKmH: '28,400 km/h',
        },
        scoreContribution: 35,
        severity: 'CRITICAL',
      },
      {
        ruleName: 'Device Change',
        isTriggered: false,
        reason: 'Device fingerprint DEV-7821-WIN matches previous authenticated sessions.',
        evidence: 'Known device fingerprint recorded in 12 prior sessions.',
        scoreContribution: 0,
        severity: 'LOW',
      },
      {
        ruleName: 'Multiple Failed Login',
        isTriggered: false,
        reason: 'No failed login attempts preceded this transaction.',
        evidence: '0 failed attempts in preceding 24 hours.',
        scoreContribution: 0,
        severity: 'LOW',
      },
    ],
  },
  'TXN-10235': {
    transactionId: 'TXN-10235',
    riskScore: 72,
    riskLevel: 'HIGH',
    explanation:
      'This transaction was flagged due to a sudden new device login combined with rapid offshore wire routing.',
    summary: 'High risk detected from new device fingerprint and velocity.',
    evaluatedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    rules: [
      {
        ruleName: 'Device Change',
        isTriggered: true,
        reason: 'First transaction initiated from an unverified mobile device.',
        evidence: 'New device fingerprint DEV-9912-IOS registered 2 minutes prior.',
        scoreContribution: 40,
        severity: 'HIGH',
      },
      {
        ruleName: 'Unusual Time',
        isTriggered: true,
        reason: 'Transaction initiated outside standard user behavioral hours.',
        evidence: 'Initiated at 03:42 AM local user time (standard window: 08:00 - 22:00).',
        scoreContribution: 32,
        severity: 'MEDIUM',
      },
      {
        ruleName: 'Unusual Amount',
        isTriggered: false,
        reason: 'Amount is within expected standard remittance limits.',
        evidence: '$1,250 within historical bracket ($500 - $2,000).',
        scoreContribution: 0,
        severity: 'LOW',
      },
    ],
  },
  'TXN-10238': {
    transactionId: 'TXN-10238',
    riskScore: 95,
    riskLevel: 'CRITICAL',
    explanation:
      'Critical risk transaction: blacklisted P2P recipient identifier, rapid multi-channel cash-out attempt, and anomalous proxy IP network.',
    summary: 'Multiple critical rules triggered including blacklisted merchant entity.',
    evaluatedAt: new Date(Date.now() - 150 * 60000).toISOString(),
    rules: [
      {
        ruleName: 'Unusual Amount',
        isTriggered: true,
        reason: 'Largest single transaction ever attempted on this user account.',
        evidence: '₹95,000 is 45x larger than account 90-day moving average.',
        scoreContribution: 40,
        severity: 'CRITICAL',
      },
      {
        ruleName: 'Transaction Velocity',
        isTriggered: true,
        reason: '5th consecutive high-value transfer in under 30 minutes.',
        evidence: 'Rapid sequence transfer pattern detected.',
        scoreContribution: 30,
        severity: 'CRITICAL',
      },
      {
        ruleName: 'Blacklisted Country',
        isTriggered: true,
        reason: 'Destination routing proxy flagged on high-risk IP database.',
        evidence: 'IP 157.34.19.88 matched known Tor/VPN exit node.',
        scoreContribution: 25,
        severity: 'CRITICAL',
      },
    ],
  },
};
